## Single question test

In [42]:
import numpy as np

answer_matrix : np.matrix = np.matrix([[0, 1, 0], [1, 0, 0], [0, 0, 1]])
answer : np.matrix = np.matrix([[0], [1], [0]])
result : np.matrix = answer_matrix * answer
result

matrix([[1],
        [0],
        [0]])

In [43]:
import numpy as np
def compute_answers(answer_matrices : np.matrix, answers : np.matrix):
    ans = np.matrix([[0.0] for _ in range(len(answers[0]))])
    for i in range(len(answer_matrices)):
        ans += answer_matrices[i] * answers[i]
    ans *= 1/len(answer_matrices)
    return ans
compute_answers([answer_matrix], [answer])

matrix([[1.],
        [0.],
        [0.]])

In [44]:
ALPHABET = list("ABCDEFGHIJKLMNOPQRSTUVWXYZ")
def ask_question(question, anslist):
    print(question+"\n")
    for i in range(len(anslist)):
        print(ALPHABET[i]+": "+anslist[i])
    while True:
        response = input()
        if (response.upper() in ALPHABET and len(response) == 1):
            break
        elif response in anslist:
            response = ALPHABET[anslist.index(response)]
            break
        else:
            print("Incorrect answer given.")
    return np.matrix([[float(ALPHABET[i] in response)] for i in range(len(anslist))])
ask_question("rizz?", ["yes", "no", "ohio"])

rizz?

A: yes
B: no
C: ohio


matrix([[1.],
        [0.],
        [0.]])

In [45]:
resp, resp_mat = [], []
for i in range(5):
    resp.append(ask_question("rizz?", ["yes", "no", "ohio"]))
    resp_mat.append(np.identity(3))
compute_answers(resp_mat, resp)

rizz?

A: yes
B: no
C: ohio
rizz?

A: yes
B: no
C: ohio
rizz?

A: yes
B: no
C: ohio
rizz?

A: yes
B: no
C: ohio
rizz?

A: yes
B: no
C: ohio


matrix([[0.6],
        [0.2],
        [0.2]])

In [211]:
expected_vector = np.matrix([[1.0], [0.0], [0.0]])
resulted_vector = np.matrix([[0.0], [1.0], [0.0]])
current_matrix = np.matrix([[1/9, 1/9, 1/9], [1/9, 1/9, 1/9], [1/9, 1/9, 1/9]])


In [231]:
SCALE_FACTOR = 0.1
inv = np.transpose(expected_vector)
a = np.vstack([inv, inv, inv])
b = np.hstack([resulted_vector, resulted_vector, resulted_vector])
free_slots = 1 / (3 * 3 - 1)
delta_matrix = (b * a / (3))*(1 + free_slots) - free_slots
current_matrix += delta_matrix*SCALE_FACTOR
current_matrix


matrix([[-0.13888889, -0.13888889, -0.13888889],
        [ 2.11111111, -0.13888889, -0.13888889],
        [-0.13888889, -0.13888889, -0.13888889]])