## Single question test

In [2]:
import numpy as np

answer_matrix : np.matrix = np.matrix([[0, 1, 0], [1, 0, 0], [0, 0, 1]])
answer : np.matrix = np.matrix([[0], [1], [0]])
result : np.matrix = answer_matrix * answer
result

matrix([[1],
        [0],
        [0]])

In [3]:
import numpy as np
def compute_answers(answer_matrices : np.matrix, answers : np.matrix):
    ans = np.matrix([[0.0] for _ in range(len(answers[0]))])
    for i in range(len(answer_matrices)):
        ans += answer_matrices[i] * answers[i]
    ans *= 1/len(answer_matrices)
    return ans
compute_answers([answer_matrix], [answer])

matrix([[1.],
        [0.],
        [0.]])

In [4]:
ALPHABET = list("ABCDEFGHIJKLMNOPQRSTUVWXYZ")
def ask_question(question, anslist):
    print(question+"\n")
    for i in range(len(anslist)):
        print(ALPHABET[i]+": "+anslist[i])
    while True:
        response = input()
        if (response.upper() in ALPHABET and len(response) == 1):
            break
        elif response in anslist:
            response = ALPHABET[anslist.index(response)]
            break
        else:
            print("Incorrect answer given.")
    return np.matrix([[float(ALPHABET[i] in response)] for i in range(len(anslist))])
ask_question("rizz?", ["yes", "no", "ohio"])

rizz?

A: yes
B: no
C: ohio


matrix([[1.],
        [0.],
        [0.]])

In [5]:
resp, resp_mat = [], []
for i in range(5):
    resp.append(ask_question("rizz?", ["yes", "no", "ohio"]))
    resp_mat.append(np.identity(3))
compute_answers(resp_mat, resp)

rizz?

A: yes
B: no
C: ohio
rizz?

A: yes
B: no
C: ohio
rizz?

A: yes
B: no
C: ohio
rizz?

A: yes
B: no
C: ohio
rizz?

A: yes
B: no
C: ohio


matrix([[0.4],
        [0.2],
        [0.2]])

In [185]:
expected_vector = np.matrix([[1.0], [0.0], [0.0]])
resulted_vector = np.matrix([[0.0], [1.0], [0.0]])
current_matrix = np.matrix(np.zeros(shape=(3,3)))
operations = 1
current_matrix.sum()


0.0

In [715]:
def adjust(mat : np.matrix, vectors: list[(np.matrix, np.matrix)]):
    global operations
    for i in range(len(vectors)):
        resulted_vector, expected_vector = vectors[i]
        inv = np.transpose(expected_vector)
        a = np.vstack([inv, inv, inv])
        b = np.hstack([resulted_vector, resulted_vector, resulted_vector])
        free_slots = 1 / (3 * 3 - 1)
        delta_matrix = (b * a / (3))*(1 + free_slots) - free_slots
        current_matrix = (mat*operations + delta_matrix)/(operations+1)
        operations += 1
    return current_matrix
current_matrix = adjust(current_matrix, [(resulted_vector, expected_vector) for _ in range(1000)])
current_matrix

matrix([[-0.12476128, -0.12476128, -0.12476128],
        [ 0.99809024, -0.12476128, -0.12476128],
        [-0.12476128, -0.12476128, -0.12476128]])